package de.dhbwheidenheim.informatik.assfalg.personspring.controller;

public class Websites {
	public static String home() {
		return ("<html>\r\n"
				+ "<head>\r\n"
				+ "  <title>Java PE Server</title>\r\n"
				+ "  <style>\r\n"
				+ "  .center-screen {\r\n"
				+ "    display: flex;\r\n"
				+ "    flex-direction: column;\r\n"
				+ "    justify-content: center;\r\n"
				+ "    align-items: center;\r\n"
				+ "    text-align: center;\r\n"
				+ "    min-height: 100vh;\r\n"
				+ "  }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "  <div class=\"center-screen\">\r\n"
				+ "    <h1>This is the server of the Java Programm TIN19</h1>\r\n"
				+ "    -> Here your advert could appeare soon! <-\r\n"
				+ "  </div>\r\n"
				+ "</body>\r\n"
				+ "</html>\r\n"
				+ ""); 
	}
	
	public static String error() {
		return ("<html>\r\n"
				+ "<head>\r\n"
				+ "  <title>Java PE Server</title>\r\n"
				+ "  <style>\r\n"
				+ "  .center-screen {\r\n"
				+ "    display: flex;\r\n"
				+ "    flex-direction: column;\r\n"
				+ "    justify-content: center;\r\n"
				+ "    align-items: center;\r\n"
				+ "    text-align: center;\r\n"
				+ "    min-height: 100vh;\r\n"
				+ "  }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "  <div class=\"center-screen\">\r\n"
				+ "    <h1>Server Information</h1>\r\n"
				+ "    An error occured. Please restart the application or try again later.\r\n"
				+ "  </div>\r\n"
				+ "  </body>\r\n"
				+ "</html>");
	}
	
	public static String occupied() {
		return("<html>\r\n"
				+ "<head>\r\n"
				+ "  <title>Java PE Server</title>\r\n"
				+ "  <style>\r\n"
				+ "  .center-screen {\r\n"
				+ "    display: flex;\r\n"
				+ "    flex-direction: column;\r\n"
				+ "    justify-content: center;\r\n"
				+ "    align-items: center;\r\n"
				+ "    text-align: center;\r\n"
				+ "    min-height: 100vh;\r\n"
				+ "  }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "  <div class=\"center-screen\">\r\n"
				+ "    <h1>Server Information</h1>\r\n"
				+ "    All current rooms are occupied. Please try again later.\r\n"
				+ "  </div>\r\n"
				+ "  </body>\r\n"
				+ "</html>");
	}
	
	public static String rooms(boolean[] r) {
		return("<html>\r\n"
				+ "<head>\r\n"
				+ "  <title>Java PE Server</title>\r\n"
				+ "  <style>\r\n"
				+ "  .center-screen {\r\n"
				+ "    display: flex;\r\n"
				+ "    flex-direction: column;\r\n"
				+ "    justify-content: center;\r\n"
				+ "    align-items: center;\r\n"
				+ "    text-align: center;\r\n"
				+ "    min-height: 100vh;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  td{\r\n"
				+ "    border-bottom: 2px solid crimson;\r\n"
				+ "    text-align: center;\r\n"
				+ "    vertical-align: middle;\r\n"
				+ "  }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "  <div class=\"center-screen\">\r\n"
				+ "    <table>\r\n"
				+ "      <tr>\r\n"
				+ "        <td><b>Room 1</b></td>\r\n"
				+ "        <td><b>Room 2</b></td>\r\n"
				+ "        <td><b>Room 3</b></td>\r\n"
				+ "      </tr>\r\n"
				+ "      <tr>\r\n"
				+ "        <td>" + r[0] + "</td>\r\n"
				+ "        <td>" + r[1] + "</td>\r\n"
				+ "        <td>" + r[2] + "</td>\r\n"
				+ "      </tr>\r\n"
				+ "    </table>\r\n"
				+ "  </div>\r\n"
				+ "</body>\r\n"
				+ "</html>\r\n"
				+ "");
	}
}
